export const companyParams=[
    { id:1,
      fieldName:'companyId',
      searchable: true,
      width: '[15%]' },
    { id:2,
      fieldName:'adminname',
      searchable: true,
      width: '[15%]' },
    { id:3,
      fieldName:'companyname',
      searchable: true,
      width: '[20%]' },
    { id:4,
      fieldName:'email',
      searchable: false,
      date: false,
      width: '[15%]' },
    { id:5,
      fieldName:'website',
      searchable: false,
      date: false,
      width: '[15%]' },
    { id:6,
      fieldName:'country',
      searchable: true,
      date: false,
      width: '[20%]' },
  ]

