export const rfpParams=[
    { id:1,
      fieldName:'companyId',
      searchable: true,
      width: '[15%]' },
    { id:2,
      fieldName:'companyname',
      searchable: true,
      width: '[15%]' },
    { id:3,
      fieldName:'name',
      searchable: true,
      width: '[15%]' },
    { id:4,
        fieldName:'contestType',
        searchable: false,
        date:false,
        width: '[15%]' },
    { id:5,
      fieldName:'openDate',
      searchable: true,
      date:true,
      width: '[15%]' },
    { id:6,
      fieldName:'endReceivingDate',
      searchable: true,
      date:true,
      width: '[15%]' },
    { id:7,
      fieldName:'endDate',
      searchable: true,
      date:true,
      width: '[15%]' }
  ]
