// Polygon Pro-pon smart contract address

// Mumbai
export const CONTRACT_ADDRESS_DATA =
  process.env.NEXT_PUBLIC_DATA_CONTRACT_ADDRESS
export const CONTRACT_ADDRESS_LOGIC =
  process.env.NEXT_PUBLIC_LOGIC_CONTRACT_ADDRESS

// console.log("CONTRACT_ADDRESS_DATA1", CONTRACT_ADDRESS_DATA1)
// console.log("CONTRACT_ADDRESS_LOGIC1", CONTRACT_ADDRESS_LOGIC1)

// export const CONTRACT_ADDRESS_DATA =
//   "0x67C4171EbE5dae31088d4CB950579e657B5ddb8b" // Nov 2, 2023
// export const CONTRACT_ADDRESS_LOGIC =
//   "0x6F41A50c3E2e2C7Efe5E1ddA221950091bca1301" // Nov 2, 2023

console.log("CONTRACT_ADDRESS_DATA", CONTRACT_ADDRESS_DATA)
console.log("CONTRACT_ADDRESS_LOGIC", CONTRACT_ADDRESS_LOGIC)
